/* This file is generated by zits. Do not edit manually */

export enum LudothequeUnitEnum {
	Playset = 'Playset',
}

/**
 * -------------------------------------------------------------------------------------------------
 * Declaration of this zome's link types
 * -------------------------------------------------------------------------------------------------
 * List of all link kinds handled by this Zome
 */
export enum LudothequeLinkType {
	All = 'All',
}
