/* This file is generated by zits. Do not edit manually */

export enum PlaysetUnitEnum {
	SvgMarker = 'SvgMarker',
	EmojiGroup = 'EmojiGroup',
	Template = 'Template',
	Space = 'Space',
}

/**
 * -------------------------------------------------------------------------------------------------
 * Declaration of this zome's link types
 * -------------------------------------------------------------------------------------------------
 * List of all link kinds handled by this Zome
 */
export enum PlaysetLinkType {
	All = 'All',
	SvgMarkers = 'SvgMarkers',
	EmojiGroups = 'EmojiGroups',
	Spaces = 'Spaces',
	Templates = 'Templates',
}
