/* This file is generated by zits. Do not edit manually */

export enum WhereUnitEnum {
	Here = 'Here',
	PlacementSession = 'PlacementSession',
}

/**
 * -------------------------------------------------------------------------------------------------
 * Declaration of this zome's link types
 * -------------------------------------------------------------------------------------------------
 * List of all link kinds handled by this Zome
 */
export enum WhereLinkType {
	All = 'All',
	Hide = 'Hide',
}
